services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false

    App\Bundle\ExportBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity}'
